name: Easy Gamemode
author: Tallerik
description: Setze dich mit /c in den Kreativ- und mit /s in den Ueberlebensmodus
version: 1.0.0

main: me.Tallerik.EasyGamemode.EasyGamemode

commands:
  c:
    description: Setzt dich in den Kreativmodus
    usage: /c
  s:
    description: Setzt dich in den Ueberlebensmodus
    usage: /s
  h:
    description: Setzt dich in den Hardcoremodus
    usage: /s
  sp:
    description: Setzt dich in den Spectatormodus
    usage: /s
  easygamemode:
    description: Informationen zum Plugin. Fuer befehle /easygamemode help
    usage: /easygamemode oder /easygamemode help